#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
FROM _BASE_NS_/fabric-baseos:_BASE_TAG_
ENV FABRIC_CA_HOME /etc/hyperledger/fabric-ca-server
ARG FABRIC_CA_DYNAMIC_LINK=false
RUN mkdir -p $FABRIC_CA_HOME /var/hyperledger/fabric-ca-server
COPY payload/fabric-ca-client /usr/local/bin
RUN chmod +x /usr/local/bin/fabric-ca-client
COPY payload/fabric-ca-server /usr/local/bin
RUN chmod +x /usr/local/bin/fabric-ca-server
RUN rm -f /etc/apt/sources.list
COPY payload/sources.list /etc/apt/
RUN apt-get update && apt-get install -y netcat && rm -rf /var/cache/apt

# Copy the same certificates that are currently hardcoded into the peers
ADD payload/fabric-ca.tar.bz2 $FABRIC_CA_HOME

COPY payload/confcenterdownload /usr/local/bin/
COPY payload/entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/entrypoint.sh

EXPOSE 7054

ENTRYPOINT ["entrypoint.sh"]
